const states = {
	AN: "Andaman and Nicobar Islands",
	AP: "Andhra Pradesh",
	AR: "Arunachal Pradesh",
	AS: "Assam",
	BR: "Bihar",
	CH: "Chandīgarh",
	CT: "Chhattīsgarh",
	DL: "Delhi",
	DN: "Dadra and Nagar Haveli and Daman and Diu",
	GA: "Goa",
	GJ: "Gujarat",
	HR: "Haryana",
	HP: "Himachal Pradesh",
	JK: "Jammu and Kashmīr",
	JH: "Jharkhand",
	KA: "Karnataka",
	KL: "Kerala",
	LA: "Ladakh",
	LD: "Lakshadweep",
	MP: "Madhya Pradesh",
	MH: "Maharashtra",
	MN: "Manipur",
	ML: "Meghalaya",
	MZ: "Mizoram",
	NL: "Nagaland",
	OR: "Odisha",
	PY: "Puducherry",
	PB: "Punjab",
	RJ: "Rajasthan",
	SK: "Sikkim",
	TN: "Tamil Nadu",
	TG: "Telangana",
	TR: "Tripura",
	TT: "Trinidad and Tobago",
	UP: "Uttar Pradesh",
	UT: "Uttarakhand",
	WB: "West Bengal",
};

export default states;
